In [46]:
# Database stuff
from google.cloud.sql.connector import Connector
import sqlalchemy
from getpass import getpass
import pg8000
#import psycopg2
import google.auth as auth
from google.oauth2 import service_account


import pandas as pd

In [47]:
creds = auth.load_credentials_from_file('useful-music-251918-b8ecc9855a02.json')
creds[0]

In [50]:

mode = "append"
password = getpass('Enter Password')

# build connection
def get_conn() -> pg8000.native.Connection:
    with Connector(credentials=creds[0]) as connector:
        conn = connector.connect(
            "useful-music-251918:us-central1:project-db",
            "pg8000",
            user="postgres",
            password=password,
            db="postgres"
        )
    return conn

# create connection pool
pool = sqlalchemy.create_engine(
    "postgresql+pg8000://",
    creator=get_conn,
)

Enter Password ········

In [18]:
pseof_df = pd.read_csv('pseof_all.csv', low_memory=False)
pseof_df

,agg_level_pseo,inst_level,institution,degree_level,cip_level,cipcode,grad_cohort,grad_cohort_years,geo_level,geography,...,y10_grads_nme,status_y1_grads_emp,status_y1_grads_emp_instate,status_y5_grads_emp,status_y5_grads_emp_instate,status_y10_grads_emp,status_y10_grads_emp_instate,status_y1_grads_nme,status_y5_grads_nme,status_y10_grads_nme
0,38,I,00105100,5,A,0,0,3,N,0,...,7281.0,1,1,1,1,1,1,1,1,1
1,38,I,00105100,7,A,0,0,5,N,0,...,1149.0,1,1,1,1,1,1,1,1,1
2,38,I,00105100,17,A,0,0,5,N,0,...,191.0,1,1,1,1,1,1,1,1,1
3,38,I,00105100,18,A,0,0,5,N,0,...,256.0,1,1,1,1,1,1,1,1,1
4,38,I,00105200,2,A,0,0,5,N,0,...,NaN,1,1,1,1,-1,-1,1,1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16953715,190,I,30182251,5,2,52,2016,3,D,5,...,NaN,1,1,-1,-1,-1,-1,5,-1,-1
16953716,190,I,30182251,5,2,52,2016,3,D,6,...,NaN,1,1,-1,-1,-1,-1,5,-1,-1
16953717,190,I,30182251,5,2,52,2016,3,D,7,...,NaN,1,1,-1,-1,-1,-1,5,-1,-1
16953718,190,I,30182251,5,2,52,2016,3,D,8,...,NaN,1,1,-1,-1,-1,-1,5,-1,-1
16953719,190,I,30182251,5,2,52,2016,3,D,9,...,NaN,1,1,-1,-1,-1,-1,5,-1,-1

In [44]:
pseof_sample = pseof_df.sample(10000)
pseof_sample

,agg_level_pseo,inst_level,institution,degree_level,cip_level,cipcode,grad_cohort,grad_cohort_years,geo_level,geography,...,y10_grads_nme,status_y1_grads_emp,status_y1_grads_emp_instate,status_y5_grads_emp,status_y5_grads_emp_instate,status_y10_grads_emp,status_y10_grads_emp_instate,status_y1_grads_nme,status_y5_grads_nme,status_y10_grads_nme
1484026,94,I,00698100,3,2,11,2011,5,N,0,...,NaN,1,1,-1,-1,-1,-1,5,-1,-1
11748077,190,I,00354100,5,2,42,2013,3,D,3,...,NaN,1,1,-1,-1,-1,-1,5,-1,-1
12977359,190,I,00365600,7,2,30,2011,5,D,2,...,NaN,1,1,-1,-1,-1,-1,5,-1,-1
4741710,184,I,00372400,5,2,13,0,3,D,1,...,NaN,1,1,5,5,5,5,5,5,5
3008051,184,I,00180700,7,2,24,0,5,D,3,...,NaN,5,5,5,5,5,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11918921,190,I,00357000,3,2,50,2001,5,D,9,...,NaN,5,5,5,5,5,5,5,5,5
14638758,190,I,00476500,7,2,26,2011,5,D,1,...,NaN,1,1,-1,-1,-1,-1,5,-1,-1
898441,94,I,00269800,7,2,54,2006,5,N,0,...,NaN,5,5,5,5,-1,-1,5,5,-1
2106069,142,I,00301800,5,2,5,2013,3,D,1,...,NaN,1,1,-1,-1,-1,-1,5,-1,-1
14134556,190,I,00375400,17,2,30,2006,5,D,6,...,NaN,5,5,5,5,-1,-1,5,5,-1

In [51]:
pseof_sample.to_sql(name='test', con=pool)

10000

In [37]:
rows_imported = 0
for data in pd.read_csv(f'pseof_all.csv', chunksize=1000000):

    print(f'importing rows {rows_imported} to {rows_imported + len(data)}...', end='')
    data.to_sql(name='flows', con=pool, if_exists='append')
    rows_imported += len(data)

    print(f'Done.')

C:\Users\zach1\AppData\Local\Temp\ipykernel_21436\2488065298.py:2: DtypeWarning: Columns (2,4,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for data in pd.read_csv(f'pseof_all.csv', chunksize=1000000):

importing rows 0 to 1000000...

['useful-music-251918:us-central1:project-db']: An error occurred while performing refresh. Scheduling another refresh attempt immediately
Traceback (most recent call last):
  File "C:\Users\zach1\Coding\env\mlenv\lib\site-packages\google\cloud\sql\connector\instance.py", line 402, in _refresh_task
    refresh_data = await refresh_task
  File "C:\Users\zach1\Coding\env\mlenv\lib\site-packages\google\cloud\sql\connector\instance.py", line 365, in _perform_refresh
    raise e
  File "C:\Users\zach1\Coding\env\mlenv\lib\site-packages\google\cloud\sql\connector\instance.py", line 344, in _perform_refresh
    metadata, ephemeral_cert = await asyncio.gather(
  File "C:\Users\zach1\Coding\env\mlenv\lib\site-packages\google\cloud\sql\connector\refresh_utils.py", line 98, in _get_metadata
    resp = await client_session.get(url, headers=headers, raise_for_status=True)
  File "C:\Users\zach1\Coding\env\mlenv\lib\site-packages\aiohttp\client.py", line 640, in _request
    resp.raise_for_status()
  File "C:\Users\zach1\Coding\env\mlenv\lib\site-packages\aiohttp\client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://sqladmin.googleapis.com/sql/v1beta4/projects/useful-music-251918/instances/project-db/connectSettings')

ClientResponseError: 403, message='Forbidden', url=URL('https://sqladmin.googleapis.com/sql/v1beta4/projects/useful-music-251918/instances/project-db/connectSettings')